apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: podinfo
spec:
  releaseName: backend
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    service:
      grpcService: backend